config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home'
  post 'tts', to: 'pages#tts', as: :tts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/audio.rb
class Audio < ApplicationRecord
  has_one_attached :file
  after_create :broadcast_audio

  # after create -> turbo broadcast
  def broadcast_audio
    broadcast_prepend_to(
      'audio-stream',
      target: 'audio-container',
      partial: 'audio/audio_container',
      locals: { audio: self, autoplay: true }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @audios = Audio.all.order(created_at: :desc)
  end


  def tts
    TextToSpeechJob.perform_later(audio_params[:prompt])

    redirect_to root_path, notice: "Audio is being generated. Please wait a few minutes."
  end

  private

  def audio_params
    params.permit(:prompt)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/audio/_audio.html.erb
<%= audio_tag(
  url_for(audio.file), 
  controls: true, 
  autoplay: autoplay) if audio.file.attached? %>

app/views/audio/_audio_container.html.erb
<div class="audio-container border m-5 p-5">
  <h3>Response #<%= audio.id %></h3>
  <p><%= audio.prompt %></p>
  <%= render partial: "audio/audio", locals: { audio: audio, autoplay: autoplay } %>
</div>

app/views/audio/_form.html.erb
<div class="container m-5 p-5" id="audio_form">
  <h2 class="text-2xl font-bold mb-4">Record a New Response</h2>
  <%= form_with url: tts_path, method: :post do %>
    <div class="mb-4">
      <%= text_area_tag :prompt, 
      nil, 
      rows: 4, 
      cols: 50, 
      placeholder: "Enter Text to Generate a Voice Response...", 
      class: "form-textarea mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>
    <%= submit_tag "Generate Voice", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= turbo_stream_from "audio-stream" %>
<%= render "audio/form" %>
<br />
<h2>Previous Responses</h2>
<div id="audio-container">
  <% @audios.each do |audio| %>
    <%= render partial: "audio/audio_container", locals: { 
      audio: audio, 
      autoplay: false } %>
  <% end %>
</div>